// <auto-generated />
using System;
using DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinansCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240814165338_ModifiedStudentEntity")]
    partial class ModifiedStudentEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("YurtDisiKazancHesapla.Models.Alis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Adet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HisseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HisseId");

                    b.ToTable("Alislar");
                });

            modelBuilder.Entity("YurtDisiKazancHesapla.Models.Hisse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sembol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hisseler");
                });

            modelBuilder.Entity("YurtDisiKazancHesapla.Models.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Adet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HisseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HisseId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("YurtDisiKazancHesapla.Models.Alis", b =>
                {
                    b.HasOne("YurtDisiKazancHesapla.Models.Hisse", null)
                        .WithMany("Alislar")
                        .HasForeignKey("HisseId");
                });

            modelBuilder.Entity("YurtDisiKazancHesapla.Models.Satis", b =>
                {
                    b.HasOne("YurtDisiKazancHesapla.Models.Hisse", null)
                        .WithMany("Satislar")
                        .HasForeignKey("HisseId");
                });

            modelBuilder.Entity("YurtDisiKazancHesapla.Models.Hisse", b =>
                {
                    b.Navigation("Alislar");

                    b.Navigation("Satislar");
                });
#pragma warning restore 612, 618
        }
    }
}
